spireClientUsername: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"

adminUsername: "${ADMIN_USERNAME}"
adminPassword: "${ADMIN_PASSWORD}"

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console
