spireClientUsername: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"

adminLogin: "${ADMIN_LOGIN}"
adminPassword: "${ADMIN_PASSWORD}"

serviceLogin: "${SERVICE_LOGIN}"
servicePassword: "${SERVICE_PASSWORD}"

login: "${BASIC_AUTH_USER}"
password: "${BASIC_AUTH_PASSWORD}"

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console

redis:
  host: "${REDIS_HOST}"
  password: "${REDIS_PASSWORD}"
  port: "${REDIS_PORT}"
  timeout: "${REDIS_TIMEOUT}"
  database: 0
  ssl: "${REDIS_SSL}"
  poolMinIdle: "${REDIS_POOL_MIN_IDLE}"
  poolMaxTotal: "${REDIS_POOL_MAX_TOTAL}"
  keyPrefix: "${REDIS_KEY_PREFIX}"
  key: "${REDIS_KEY}"
  ttl:
    getUserDetails: "${REDIS_TTL_GET_USER_DETAILS}"
    getUserPrivileges: "${REDIS_TTL_GET_USER_PRIVILEGES}"
