spireClientUsername: "ENTER_USERNAME_HERE"
spireClientPassword: "ENTER_PASSWORD_HERE"
spireClientUrl: "https://lite-service-mocking-dev.cloudapps.digital/spire/fox/ispire/"

jwtSharedSecret: "demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement"

adminLogin: "ENTER_USERNAME_HERE"
adminPassword: "ENTER_PASSWORD_HERE"

serviceLogin: "ENTER_USERNAME_HERE"
servicePassword: "ENTER_PASSWORD_HERE"

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

redis:
  host: localhost
  password: ""
  port: 6379
  timeout: 2000
  database: 0
  ssl: false
  poolMinIdle: 1
  poolMaxTotal: 5
  keyPrefix: local
  key: lite-user-service
  ttl:
    getUserDetails: "2 minutes"
    getUserPrivileges: "2 minutes"
