spireClientUsername: spire_user
spireClientPassword: spire_password
spireClientUrl: http://service-mocking.svc.dev.licensing.service.trade.gov.uk.test/spire/fox/ispire/
jwtSharedSecret: demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement

adminLogin: admin
adminPassword: admin

serviceLogin: service
servicePassword: service

login: user
password: pass

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

redis:
  host: localhost
  password: ""
  port: 6379
  timeout: 2000
  database: 0
  ssl: false
  poolMinIdle: 1
  poolMaxTotal: 5
  keyPrefix: local
  key: lite-user-service
  ttl:
    getUserDetails: "2 minutes"
    getUserPrivileges: "2 minutes"
