spireClientUsername: spire_user
spireClientPassword: spire_password
spireClientUrl: http://service-mocking.svc.dev.licensing.service.trade.gov.uk.test/spire/fox/ispire/
jwtSharedSecret: demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement

adminLogin: admin
adminPassword: admin

serviceLogin: service
servicePassword: service

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE